/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2.presentation.activos.listado;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sourceforge.barbecue.Barcode;
import net.sourceforge.barbecue.BarcodeFactory;
import proyecto2.Application;
import proyecto2.logic.Activo;

/**
 *
 * @author oscar
 */
public class ActivosView extends javax.swing.JInternalFrame implements java.util.Observer{

    /**
     * Creates new form ActivosView
     */
    ActivosController controller;
    ActivosModel model;
    
    public ActivosView() {
        super("",false,true);
        initComponents();
    }

    public ActivosController getController() {
        return controller;
    }

    public void setController(ActivosController controller) {
        this.controller = controller;
    }
    public ActivosModel getModel() {
        return model;
    }

    public void setModel(ActivosModel model) {
        this.model = model;
        model.addObserver(this);
    }
    
    public void fromActivo(Activo filtro){
        codigo.setText(filtro.getCodigo());
    }
    
    public Activo toActivo(){
        Activo result=new Activo();
        result.setCodigo(codigo.getText());
        return result;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        activos = new javax.swing.JTable();
        codigoFld = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        codigo = new javax.swing.JLabel();
        asignarFuncionarioButton = new javax.swing.JButton();
        imprimirButton = new javax.swing.JButton();
        label_codigoBarrasImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        activos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        activos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(activos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 385, 115));
        getContentPane().add(codigoFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 114, -1));

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo.setText("Codigo:");
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        asignarFuncionarioButton.setText("Asignar funcionario");
        asignarFuncionarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarFuncionarioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(asignarFuncionarioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        imprimirButton.setText("Imprimir ");
        imprimirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(imprimirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));
        getContentPane().add(label_codigoBarrasImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 240, 110));

        jLabel2.setText("Codigo de Barras");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        try{
            controller.buscar(this.toActivo());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void asignarFuncionarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarFuncionarioButtonActionPerformed
        // TODO add your handling code here:
        try {
            int row = this.activos.getSelectedRow();
            controller.getLabores(asignarFuncionarioButton.getLocation(), row);
        } catch (Exception ex) {
           // Logger.getLogger(JefeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asignarFuncionarioButtonActionPerformed
    Activo seleccionado;
    private void activosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activosMouseClicked
        // TODO add your handling code here:
         try{
            int row=activos.getSelectedRow();
            seleccionado= model.getActivos().getRowAt(row);
           
        }catch(Exception e){
        }
        
    }//GEN-LAST:event_activosMouseClicked

    private void imprimirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirButtonActionPerformed
        Barcode barcode = null;
        try{
            int row = activos.getSelectedRow();
            seleccionado= model.getActivos().getRowAt(row);
            barcode = BarcodeFactory.createCode39(seleccionado.getCodigo(), true);
        }catch(Exception ex){   }
        barcode.setDrawingText(true);
        
        barcode.setBarWidth(2);
        barcode.setBarHeight(60);
        BufferedImage image = new BufferedImage(300,100, BufferedImage.TYPE_INT_ARGB);
        Graphics2D graphics = (Graphics2D) image.getGraphics();
        
        try{
            barcode.draw(graphics, 5, 20);
        }catch(Exception ex){   }
        ImageIcon icon = new ImageIcon(image);
        this.label_codigoBarrasImage.setIcon(icon);
        
        
    }//GEN-LAST:event_imprimirButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable activos;
    private javax.swing.JButton asignarFuncionarioButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JLabel codigo;
    private javax.swing.JTextField codigoFld;
    private javax.swing.JButton imprimirButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_codigoBarrasImage;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        Activo filtro=model.getFilter();
        this.fromActivo(filtro);
        activos.setModel(model.getActivos());
    }
}
